Repository ita-social-projects/EPlast, pull requests merged in 2020-07, with the labels that each got.

#122 decisions binding
  EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
Labels: Configuration, bug

#123 decisions binding v2.0
  EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
Labels: Configuration

#127 VV fix bug with looping in web api
  EPlast/EPlast.BLL/DTO/UserProfiles/ShortUserInformationDTO.cs
  EPlast/EPlast.BLL/DTO/UserProfiles/UserTableDTO.cs
  EPlast/EPlast.BLL/Mapping/User/ShortUserInformationProfile.cs
  EPlast/EPlast.BLL/Services/Admin/AdminService.cs
  EPlast/EPlast.WebApi/Controllers/UserController.cs
  EPlast/EPlast.WebApi/Mapping/User/UserProfile.cs
  EPlast/EPlast.WebApi/Models/UserModels/EditUserViewModel.cs
  EPlast/EPlast.WebApi/Models/UserModels/PersonalDataViewModel.cs
  EPlast/EPlast.WebApi/Models/UserModels/UserViewModel.cs
Labels: Configuration

#128 refactoring decisions controller
  EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
  EPlast/EPlast.WebApi/Models/Decision/DecisionViewModel.cs
Labels: Configuration

#136 Br add event type filtering
  EPlast/EPlast.BLL/Interfaces/Events/IActionManager.cs
  EPlast/EPlast.BLL/Interfaces/Events/IEventCategoryManager.cs
  EPlast/EPlast.BLL/Interfaces/Events/IEventTypeManager.cs
  EPlast/EPlast.BLL/Services/Events/ActionManager.cs
  EPlast/EPlast.BLL/Services/Events/EventCategoryManager.cs
  EPlast/EPlast.BLL/Services/Events/EventTypeManager.cs
  EPlast/EPlast.WebApi/Controllers/EventsController.cs
  EPlast/EPlast.XUnitTest/Controllers/ActionControllerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/ActionManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventCategoryManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventTypeManagerTests.cs
  EPlast/EPlast/Controllers/ActionController.cs
  EPlast/EPlast/Views/Action/GetAction.cshtml
Labels: Type: Enhancement, Type: Maintenances

#137 Refactoring decisions web api controller
  EPlast/EPlast.BLL/Interfaces/AzureStorage/IDecisionBlobStorageRepository.cs
  EPlast/EPlast.BLL/Interfaces/Decesion/IDecisionService.cs
  EPlast/EPlast.BLL/Services/AzureStorage/DecisionBlobStorageRepository.cs
  EPlast/EPlast.BLL/Services/Decision/DecisionService.cs
  EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
  EPlast/EPlast.WebApi/Mapping/Decision/DecisionProfile.cs
  EPlast/EPlast.WebApi/Models/Decision/DecisionCreateViewModel.cs
  EPlast/EPlast.WebApi/Models/Decision/DecisionViewModel.cs
  EPlast/EPlast.WebApi/Startup.cs
  EPlast/EPlast.WebApi/appsettings.json
  EPlast/EPlast.XUnitTest/Services/Decision/DecisionServiceTests.cs
Labels: Configuration, bug, enhancement

#141 AS-Add NUnit Tests for Api
  EPlast/EPlast.Tests/Controllers/AccountControllerTestsAuth.cs
  EPlast/EPlast.Tests/EPlast.Tests.csproj
  EPlast/EPlast.XUnitTest/Controllers/AccountControllerTests.cs
  EPlast/EPlast.sln
Labels: Configuration

#142 fixed dependency injection bug
  EPlast/EPlast/Startup.cs
Labels: bug

#146 VV binding user profile
  EPlast/EPlast.BLL/Interfaces/UserProfiles/IUserService.cs
  EPlast/EPlast.BLL/Services/UserProfiles/UserService.cs
  EPlast/EPlast.WebApi/Controllers/UserController.cs
  EPlast/EPlast.WebApi/Mapping/User/DegreeProfile.cs
  EPlast/EPlast.WebApi/Mapping/User/ReligionProfile.cs
  EPlast/EPlast.WebApi/Mapping/User/UserProfile.cs
  EPlast/EPlast.WebApi/Mapping/User/UserProfileFields/EducationProfile.cs
  EPlast/EPlast.WebApi/Mapping/User/UserProfileFields/GenderProfile.cs
  EPlast/EPlast.WebApi/Mapping/User/UserProfileFields/NationalityProfile.cs
  EPlast/EPlast.WebApi/Mapping/User/UserProfileFields/WorkProfile.cs
  EPlast/EPlast.WebApi/Models/UserModels/EditUserViewModel.cs
  EPlast/EPlast.WebApi/Models/UserModels/PersonalDataViewModel.cs
  EPlast/EPlast.WebApi/Models/UserModels/UserEducationViewModel.cs
  EPlast/EPlast.WebApi/Models/UserModels/UserProfileFields/DegreeViewModel.cs
  EPlast/EPlast.WebApi/Models/UserModels/UserProfileFields/EducationViewModel.cs
  EPlast/EPlast.WebApi/Models/UserModels/UserProfileFields/GenderViewModel.cs
  EPlast/EPlast.WebApi/Models/UserModels/UserProfileFields/NationalityViewModel.cs
  EPlast/EPlast.WebApi/Models/UserModels/UserProfileFields/ReligionViewModel.cs
  EPlast/EPlast.WebApi/Models/UserModels/UserProfileFields/WorkViewModel.cs
  EPlast/EPlast.WebApi/Models/UserModels/UserViewModel.cs
  EPlast/EPlast.WebApi/Models/UserModels/UserWorkViewModel.cs
Labels: enhancement

#152 pdf bug
  EPlast/EPlast.BLL/Services/PDF/PDFService.cs
Labels: bug

#197 Added ProjectGuid for all projects
  EPlast/EPlast.AutomatedTest/EPlast.AutomatedTest.csproj
  EPlast/EPlast.BLL/EPlast.BLL.csproj
  EPlast/EPlast.DataAccess/EPlast.DataAccess.csproj
  EPlast/EPlast.Resources/EPlast.Resources.csproj
  EPlast/EPlast.Tests/EPlast.Tests.csproj
  EPlast/EPlast.WebApi/EPlast.WebApi.csproj
  EPlast/EPlast.XUnitTest/EPlast.XUnitTest.csproj
  EPlast/EPlast/EPlast.csproj
Labels: Configuration

#198 Id add documentation cities
  EPlast/EPlast.BLL/Interfaces/City/ICItyAdministrationService.cs
  EPlast/EPlast.BLL/Interfaces/City/ICityMembersService.cs
  EPlast/EPlast.BLL/Interfaces/City/ICityService.cs
  EPlast/EPlast.BLL/Services/AzureStorage/Base/AzureBlobConnectionFactory.cs
  EPlast/EPlast.BLL/Services/City/CityAdministrationService.cs
  EPlast/EPlast.BLL/Services/City/CityMembersService.cs
  EPlast/EPlast.BLL/Services/City/CityService.cs
  EPlast/EPlast.WebApi/Controllers/CitiesController.cs
  EPlast/EPlast.WebApi/Models/City/CitiesViewModel.cs
  EPlast/EPlast.WebApi/Models/City/PageViewModel.cs
Labels: documentation

#211 AS-add swagger documentation
  EPlast/EPlast.BLL/Interfaces/AccountAuthentication/IAccountService.cs
  EPlast/EPlast.BLL/Interfaces/AccountAuthentication/IDateTimeHelper.cs
  EPlast/EPlast.BLL/Interfaces/Auth/IAuthService.cs
  EPlast/EPlast.BLL/Interfaces/Auth/IDateTimeHelper.cs
  EPlast/EPlast.BLL/Interfaces/EmailSending/IEmailConfirmation.cs
  EPlast/EPlast.BLL/Interfaces/Home/IHomeService.cs
  EPlast/EPlast.BLL/Interfaces/Jwt/IJwtService.cs
  EPlast/EPlast.BLL/Models/Jwt/LoginModel.cs
  EPlast/EPlast.BLL/Services/Auth/AuthService.cs
  EPlast/EPlast.BLL/Services/Auth/DateTimeHelper.cs
  EPlast/EPlast.BLL/Services/EmailSending/EmailConfirmationService.cs
  EPlast/EPlast.BLL/Services/Jwt/JwtService.cs
  EPlast/EPlast.BLL/Services/Jwt/Jwtservice.cs
  EPlast/EPlast.Tests/Controllers/AuthControllerTests.cs
  EPlast/EPlast.WebApi/.config/dotnet-tools.json
  EPlast/EPlast.WebApi/Controllers/AuthController.cs
  EPlast/EPlast.WebApi/Controllers/UserController.cs
  EPlast/EPlast.WebApi/EPlast.WebApi.csproj
  EPlast/EPlast.WebApi/Startup.cs
  EPlast/EPlast.XUnitTest/Controllers/AccountControllerTests.cs
  EPlast/EPlast.XUnitTest/Controllers/AccountControllerTestsIdentity.cs
  EPlast/EPlast.XUnitTest/Services/Authentication/AccountServiceTests.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/appsettings.json
Labels: documentation

#207 Documentation and validaion for decisions
  EPlast/EPlast.BLL/DTO/Decision/DecisionDTO.cs
  EPlast/EPlast.BLL/DTO/Decision/DecisionWrapperDTO.cs
  EPlast/EPlast.BLL/Interfaces/Decesion/IDecisionService.cs
  EPlast/EPlast.BLL/Services/Decision/DecisionService.cs
  EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
  EPlast/EPlast.XUnitTest/Services/Decision/DecisionServiceTests.cs
  EPlast/EPlast/Controllers/DecisionController.cs
  EPlast/EPlast/Mapping/Decision/DecisionWrapperProfile.cs
Labels: Configuration, dependencies, enhancement

#213 Added documentation for club, fixed words in decision documentation
  EPlast/EPlast.BLL/Interfaces/Club/IClubAdministrationService.cs
  EPlast/EPlast.BLL/Interfaces/Club/IClubMembersService.cs
  EPlast/EPlast.BLL/Interfaces/Club/IClubService.cs
  EPlast/EPlast.BLL/Services/Club/ClubAdministrationService.cs
  EPlast/EPlast.BLL/Services/Club/ClubMembersService.cs
  EPlast/EPlast.BLL/Services/Club/ClubService.cs
  EPlast/EPlast.DataAccess/Entities/Club/ClubAdministration.cs
  EPlast/EPlast.WebApi/Controllers/ClubController.cs
  EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
Labels: Configuration, documentation, enhancement

#214 VV approvers page
  EPlast/EPlast.BLL/Interfaces/UserProfiles/IUserService.cs
  EPlast/EPlast.BLL/Services/UserProfiles/UserService.cs
  EPlast/EPlast.WebApi/Controllers/UserController.cs
  EPlast/EPlast.WebApi/Mapping/Approver/ApproverProfile.cs
  EPlast/EPlast.WebApi/Mapping/Approver/ConfirmedUserProfile.cs
  EPlast/EPlast.WebApi/Mapping/User/UserProfileFields/DegreeProfile.cs
  EPlast/EPlast.WebApi/Mapping/User/UserProfileFields/ReligionProfile.cs
  EPlast/EPlast.WebApi/Models/Approver/ApproverViewModel.cs
  EPlast/EPlast.WebApi/Models/Approver/ConfirmedUserViewModel.cs
  EPlast/EPlast.WebApi/Models/UserModels/UserApproversViewModel.cs
  EPlast/EPlast.XUnitTest/Services/UserArea/UserServiceTests.cs
Labels: enhancement

#215 Br add swagger documentation
  EPlast/EPlast.BLL/Interfaces/Events/IActionManager.cs
  EPlast/EPlast.BLL/Interfaces/Events/IEventCategoryManager.cs
  EPlast/EPlast.BLL/Interfaces/Events/IEventStatusManager.cs
  EPlast/EPlast.BLL/Interfaces/Events/IEventTypeManager.cs
  EPlast/EPlast.BLL/Interfaces/Events/IParticipantManager.cs
  EPlast/EPlast.BLL/Interfaces/Events/IParticipantStatusManager.cs
  EPlast/EPlast.BLL/Services/Events/ActionManager.cs
  EPlast/EPlast.BLL/Services/Events/EventCategoryManager.cs
  EPlast/EPlast.BLL/Services/Events/EventStatusManager.cs
  EPlast/EPlast.BLL/Services/Events/EventTypeManager.cs
  EPlast/EPlast.BLL/Services/Events/ParticipantManager.cs
  EPlast/EPlast.BLL/Services/Events/ParticipantStatusManager.cs
  EPlast/EPlast.WebApi/Controllers/EventsController.cs
Labels: documentation

#217 Vv user documentation
  EPlast/EPlast.BLL/Interfaces/Admin/IAdminService.cs
  EPlast/EPlast.BLL/Interfaces/AzureStorage/Base/IAzureBlobConnectionFactory.cs
  EPlast/EPlast.BLL/Interfaces/AzureStorage/Base/IBlobStorageRepository.cs
  EPlast/EPlast.BLL/Interfaces/UserProfiles/IDegreeService.cs
  EPlast/EPlast.BLL/Interfaces/UserProfiles/IEducationService.cs
  EPlast/EPlast.BLL/Interfaces/UserProfiles/IGenderService.cs
  EPlast/EPlast.BLL/Interfaces/UserProfiles/INationalityService.cs
  EPlast/EPlast.BLL/Interfaces/UserProfiles/IReligionService.cs
  EPlast/EPlast.BLL/Interfaces/UserProfiles/IUserService.cs
  EPlast/EPlast.BLL/Interfaces/UserProfiles/IWorkService.cs
  EPlast/EPlast.BLL/Services/Admin/AdminService.cs
  EPlast/EPlast.BLL/Services/AzureStorage/Base/AzureBlobConnectionFactory.cs
  EPlast/EPlast.BLL/Services/AzureStorage/Base/BlobStorageRepository.cs
  EPlast/EPlast.BLL/Services/UserProfiles/DegreeService.cs
  EPlast/EPlast.BLL/Services/UserProfiles/EducationService.cs
  EPlast/EPlast.BLL/Services/UserProfiles/GenderService.cs
  EPlast/EPlast.BLL/Services/UserProfiles/NationalityService.cs
  EPlast/EPlast.BLL/Services/UserProfiles/ReligionService.cs
  EPlast/EPlast.BLL/Services/UserProfiles/UserService.cs
  EPlast/EPlast.BLL/Services/UserProfiles/WorkService.cs
  EPlast/EPlast.WebApi/Controllers/AdminController.cs
  EPlast/EPlast.WebApi/Controllers/UserController.cs
  EPlast/EPlast.WebApi/Startup.cs
  EPlast/EPlast.WebApi/appsettings.json
Labels: enhancement

#204 Task#185 Added Unit tests for EventsConroller
  EPlast/EPlast.Tests/Controllers/EventsControllerTests.cs
Labels: Status: Review Needed, good first issue
