Repository ita-social-projects/EPlast, pull requests merged in 2020-05, with the labels that each got.

#10 VV Add _ProfileLayout for personal data of user
  EPlast/EPlast.DataAccess/Entities/Account/User.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/ViewModels/UserViewModel.cs
  EPlast/EPlast/Views/Account/Approvers.cshtml
  EPlast/EPlast/Views/Account/Edit.cshtml
  EPlast/EPlast/Views/Account/Positions.cshtml
  EPlast/EPlast/Views/Account/UserProfile.cshtml
  EPlast/EPlast/Views/Account/_ProfileLayout.cshtml
  EPlast/EPlast/Views/EventUser/EventUser.cshtml
  EPlast/EPlast/wwwroot/uncompiled/sass/EventUser.scss
  EPlast/EPlast/wwwroot/uncompiled/sass/editUserPage.scss
  EPlast/EPlast/wwwroot/uncompiled/sass/userProfile.scss
Labels: enhancement

#18 Update README.md
  README.md
Labels: documentation

#20 AS-CodeRefactoring
  EPlast/EPlast.BussinessLayer/DTO/Account/ChangePasswordDto.cs
  EPlast/EPlast.BussinessLayer/DTO/Account/ContactsDto.cs
  EPlast/EPlast.BussinessLayer/DTO/Account/ForgotPasswordDto.cs
  EPlast/EPlast.BussinessLayer/DTO/Account/LoginDto.cs
  EPlast/EPlast.BussinessLayer/DTO/Account/RegisterDto.cs
  EPlast/EPlast.BussinessLayer/DTO/Account/ResetPasswordDto.cs
  EPlast/EPlast.BussinessLayer/EPlast.BussinessLayer.csproj
  EPlast/EPlast.BussinessLayer/Interfaces/IAccountService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/IDateTimeHelper.cs
  EPlast/EPlast.BussinessLayer/Services/AccountService.cs
  EPlast/EPlast.BussinessLayer/Services/DateTimeHelper.cs
  EPlast/EPlast.DataAccess/Entities/Account/User.cs
  EPlast/EPlast.XUnitTest/AccountControllerTestsIdentity.cs
  EPlast/EPlast.XUnitTest/Controllers/AccountControllerTestsIdentity.cs
  EPlast/EPlast.XUnitTest/EPlast.XUnitTest.csproj
  EPlast/EPlast.XUnitTest/Services/AccountServiceTests.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Mapping/ChangePasswordProfile.cs
  EPlast/EPlast/Mapping/ForgotPasswordProfile.cs
  EPlast/EPlast/Mapping/LoginProfile.cs
  EPlast/EPlast/Mapping/RegisterProfile.cs
  EPlast/EPlast/Mapping/ResetPasswordProfile.cs
  EPlast/EPlast/Mapping/UserProfile.cs
  EPlast/EPlast/Mapping/UserProfileProfile.cs
  EPlast/EPlast/Startup.cs
Labels: Configuration, Status: Review Needed, dependencies, documentation

#32 VV fix problems
  EPlast/EPlast.XUnitTest/AccountControllerTests.cs
  EPlast/EPlast.XUnitTest/Controllers/AccountControllerTestsIdentity.cs
  EPlast/EPlast.XUnitTest/EPlast.XUnitTest.csproj
  EPlast/EPlast/Controllers/AccountController.cs
Labels: Configuration

#27 Event view fixes. Error view changes
  .gitignore
  EPlast/EPlast.XUnitTest/EventUserControllerTests.cs
  EPlast/EPlast/Controllers/ErrorController.cs
  EPlast/EPlast/Controllers/EventUserController.cs
  EPlast/EPlast/Views/Account/_ProfileLayout.cshtml
  EPlast/EPlast/Views/Error/Error.cshtml
  EPlast/EPlast/Views/Error/PageNotFound.cshtml
  EPlast/EPlast/Views/Error/_ErrorLayout.cshtml
  EPlast/EPlast/Views/EventUser/EventCreate.cshtml
  EPlast/EPlast/Views/EventUser/EventUser.cshtml
Labels: Status: Review Needed, Type: Bug, Type: Maintenances

#33 VV-add city service
  EPlast/EPlast.BussinessLayer/DTO/City/CityAdministrationDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/City/CityDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/City/CityDocumentTypeDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/City/CityDocumentsDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/City/CityMembersDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/City/CityProfileDTO.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityAdministrationService.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityService.cs
  EPlast/EPlast.BussinessLayer/Services/CityService.cs
  EPlast/EPlast.BussinessLayer/Services/Interfaces/ICItyAdministrationService.cs
  EPlast/EPlast.BussinessLayer/Services/Interfaces/ICityService.cs
  EPlast/EPlast.BussinessLayer/Services/UserService.cs
  EPlast/EPlast.XUnitTest/AdminControllerTests.cs
  EPlast/EPlast.XUnitTest/CityControllerTests.cs
  EPlast/EPlast/Controllers/AdminController.cs
  EPlast/EPlast/Controllers/CItyController.cs
  EPlast/EPlast/Mapping/City/CityAdministrationProfile.cs
  EPlast/EPlast/Mapping/City/CityDocumentTypeProfile.cs
  EPlast/EPlast/Mapping/City/CityDocumentsProfile.cs
  EPlast/EPlast/Mapping/City/CityMembersProfile.cs
  EPlast/EPlast/Mapping/City/CityProfile.cs
  EPlast/EPlast/Mapping/City/CityProfileProfile.cs
  EPlast/EPlast/Mapping/CityProfile.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/ViewModels/City/CityAdministrationViewModel.cs
  EPlast/EPlast/ViewModels/City/CityDocumentTypeViewModel.cs
  EPlast/EPlast/ViewModels/City/CityDocumentViewModel.cs
  EPlast/EPlast/ViewModels/City/CityMembersViewModel.cs
  EPlast/EPlast/ViewModels/City/CityProfileViewModel.cs
  EPlast/EPlast/ViewModels/City/CityViewModel.cs
  EPlast/EPlast/ViewModels/CityViewModel.cs
  EPlast/EPlast/ViewModels/EditCityViewModel.cs
  EPlast/EPlast/ViewModels/RegionsAdminsViewModel.cs
  EPlast/EPlast/Views/Admin/GetAdmins.cshtml
  EPlast/EPlast/Views/Admin/RegionsAdmins.cshtml
  EPlast/EPlast/Views/City/CityAdmins.cshtml
  EPlast/EPlast/Views/City/CityDocuments.cshtml
  EPlast/EPlast/Views/City/CityFollowers.cshtml
  EPlast/EPlast/Views/City/CityMembers.cshtml
  EPlast/EPlast/Views/City/CityProfile.cshtml
  EPlast/EPlast/Views/City/Create.cshtml
  EPlast/EPlast/Views/City/Details.cshtml
  EPlast/EPlast/Views/City/Edit.cshtml
  EPlast/EPlast/Views/City/Index.cshtml
Labels: enhancement

#38 AB-Refactoring
  EPlast/EPlast.BussinessLayer/AccessManagers/CitiesGetters/CitiesGetterForAdmin.cs
  EPlast/EPlast.BussinessLayer/AccessManagers/CitiesGetters/CitiesGetterForCityAdmin.cs
  EPlast/EPlast.BussinessLayer/AccessManagers/CitiesGetters/CitiesGetterForRegionAdmin.cs
  EPlast/EPlast.BussinessLayer/AccessManagers/CityAccessManager.cs
  EPlast/EPlast.BussinessLayer/AccessManagers/CityAccessManagerSettings.cs
  EPlast/EPlast.BussinessLayer/AccessManagers/Interfaces/ICitiesGetter.cs
  EPlast/EPlast.BussinessLayer/AccessManagers/Interfaces/ICityAccessManager.cs
  EPlast/EPlast.BussinessLayer/AccessManagers/Interfaces/ICityAccessManagerSettings.cs
  EPlast/EPlast.BussinessLayer/DTO/AnnualReportDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/AnnualReportStatus.cs
  EPlast/EPlast.BussinessLayer/DTO/CityLegalStatusDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/CityLegalStatusType.cs
  EPlast/EPlast.BussinessLayer/DTO/CityManagementDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/MembersStatisticDTO.cs
  EPlast/EPlast.BussinessLayer/Exceptions/AnnualReportException.cs
  EPlast/EPlast.BussinessLayer/Services/AnnualReportService.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityAccess/CityAccessGetters/CItyAccessForRegionAdminGetter.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityAccess/CityAccessGetters/CityAccessForAdminGetter.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityAccess/CityAccessGetters/CityAccessForCityAdminGetter.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityAccess/CityAccessGetters/ICItyAccessGetter.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityAccess/CityAccessService.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityMembersService.cs
  EPlast/EPlast.BussinessLayer/Services/Interfaces/IAnnualReportService.cs
  EPlast/EPlast.BussinessLayer/Services/Interfaces/ICityAccessService.cs
  EPlast/EPlast.BussinessLayer/Services/Interfaces/ICityMembersService.cs
  EPlast/EPlast.BussinessLayer/Settings/CityAccessSettings.cs
  EPlast/EPlast/Controllers/DocumentationController.cs
  EPlast/EPlast/Mapping/AnnualReportProfile.cs
  EPlast/EPlast/Mapping/CityLegalStatusProfile.cs
  EPlast/EPlast/Mapping/CityManagementProfile.cs
  EPlast/EPlast/Mapping/MembersStatisticProfile.cs
  EPlast/EPlast/Models/Enums/AnnualReportOperation.cs
  EPlast/EPlast/Models/Enums/AnnualReportStatus.cs
  EPlast/EPlast/Models/Enums/CityLegalStatusType.cs
  EPlast/EPlast/Models/ViewModelInitializations/AnnualReportVMInitializer.cs
  EPlast/EPlast/Models/ViewModelInitializations/Interfaces/IAnnualReportVMInitializer.cs
  EPlast/EPlast/Models/ViewModelInitializations/Interfaces/IViewAnnualReportsVMInitializer.cs
  EPlast/EPlast/Models/ViewModelInitializations/ViewAnnualReportsVMInitializer.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/ViewModels/AnnualReportViewModel.cs
  EPlast/EPlast/ViewModels/CityLegalStatusViewModel.cs
  EPlast/EPlast/ViewModels/CityManagementViewModel.cs
  EPlast/EPlast/ViewModels/CreateEditAnnualReportViewModel.cs
  EPlast/EPlast/ViewModels/MembersStatisticViewModel.cs
  EPlast/EPlast/ViewModels/ViewAnnualReportsViewModel.cs
  EPlast/EPlast/Views/Documentation/CreateEditAnnualReport.cshtml
  EPlast/EPlast/Views/Documentation/ViewAnnualReportsAsync.cshtml
  EPlast/EPlast/Views/Documentation/_GetAnnualReport.cshtml
  EPlast/EPlast/Views/Shared/_Layout.cshtml
  EPlast/EPlast/wwwroot/uncompiled/ts/annualReport.js
  EPlast/EPlast/wwwroot/uncompiled/ts/annualReport.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/annualReport.ts
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.ts
Labels: Status: Review Needed

#40 Br event user refactoring
  EPlast/EPlast.BussinessLayer/DTO/EventUser/CreateEventAdminDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/EventUser/EventAdministrationDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/EventUser/EventCreateDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/EventUser/EventDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/EventUser/EventGeneralInfoDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/EventUser/EventTypeDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/EventUser/EventUserDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/EventUser/UserDTO.cs
  EPlast/EPlast.BussinessLayer/Interfaces/EventUser/IEventUserManager.cs
  EPlast/EPlast.BussinessLayer/Interfaces/Events/EventAdminManager.cs
  EPlast/EPlast.BussinessLayer/Interfaces/Events/IParticipantManager.cs
  EPlast/EPlast.BussinessLayer/Mapping/EventUser/EventGeneralInfoProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/EventUser/EventProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/EventUser/EventTypeProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/EventUser/UserProfile.cs
  EPlast/EPlast.BussinessLayer/Services/EventUser/EventUserManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/EventAdminManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/ParticipantManager.cs
  EPlast/EPlast.DataAccess/Entities/EventAdministration.cs
  EPlast/EPlast.XUnitTest/EventUserControllerTests.cs
  EPlast/EPlast/Controllers/EventUserController.cs
  EPlast/EPlast/Mapping/EventUser/CreateEventAdminProfile.cs
  EPlast/EPlast/Mapping/EventUser/EventAdministrationProfile.cs
  EPlast/EPlast/Mapping/EventUser/EventCreateProfile.cs
  EPlast/EPlast/Mapping/EventUser/EventGeneralInfoProfile.cs
  EPlast/EPlast/Mapping/EventUser/EventProfile.cs
  EPlast/EPlast/Mapping/EventUser/EventTypeProfile.cs
  EPlast/EPlast/Mapping/EventUser/EventUserProfile.cs
  EPlast/EPlast/Mapping/EventUser/UserProfile.cs
  EPlast/EPlast/Mapping/Events/ActionCategoryProfile.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/ViewModels/EventCreateViewModel.cs
  EPlast/EPlast/ViewModels/EventUser/CreateEventAdminViewModel.cs
  EPlast/EPlast/ViewModels/EventUser/EventAdministrationViewModel.cs
  EPlast/EPlast/ViewModels/EventUser/EventCreateViewModel.cs
  EPlast/EPlast/ViewModels/EventUser/EventGeneralInfoViewModel.cs
  EPlast/EPlast/ViewModels/EventUser/EventTypeViewModel.cs
  EPlast/EPlast/ViewModels/EventUser/EventUserViewModel.cs
  EPlast/EPlast/ViewModels/EventUser/EventViewModel.cs
  EPlast/EPlast/ViewModels/EventUser/UserViewModel.cs
  EPlast/EPlast/ViewModels/Events/EventUserViewModel.cs
  EPlast/EPlast/Views/EventUser/EventCreate.cshtml
  EPlast/EPlast/Views/EventUser/EventEdit.cshtml
  EPlast/EPlast/Views/EventUser/EventUser.cshtml
  EPlast/EPlast/Views/EventUser/SetAdministration.cshtml
  EPlast/EPlast/Views/EventUser/_EventInfoModals.cshtml
Labels: Configuration, Status: Review Needed

#36 AS-Add Resource File
  EPlast/EPlast.BussinessLayer/Services/AccountService.cs
  EPlast/EPlast.BussinessLayer/Services/EmailConfirmation.cs
  EPlast/EPlast.Resources/AuthenticationErrors.cs
  EPlast/EPlast.Resources/AuthenticationErrors.uk.Designer.cs
  EPlast/EPlast.Resources/AuthenticationErrors.uk.resx
  EPlast/EPlast.Resources/EPlast.Resources.csproj
  EPlast/EPlast.XUnitTest/AccountControllerTests.cs
  EPlast/EPlast.XUnitTest/Controllers/AccountControllerTestsIdentity.cs
  EPlast/EPlast.XUnitTest/EPlast.XUnitTest.csproj
  EPlast/EPlast.XUnitTest/Services/AccountServiceTests.cs
  EPlast/EPlast.sln
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/EPlast.csproj
  EPlast/EPlast/Startup.cs
Labels: Configuration, Status: Review Needed, dependencies

#35 Change namespaces
  EPlast/EPlast.BussinessLayer/DTO/AnnualReportDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/ApproverDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/City/CityAdministrationDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/City/CityMembersDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/CityManagementDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/ConfirmedUserDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/DegreeDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/EducationDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/GenderDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/NationalityDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/ReligionDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/UserDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/UserProfileDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/WorkDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserTableDTO.cs
  EPlast/EPlast.BussinessLayer/Interfaces/City/ICItyAdministrationService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/City/ICityService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/IAccountService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/IAdminService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/IConfirmedUsersService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/ILoggerService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/IUserManagerService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserProfiles/IDegreeService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserProfiles/IEducationService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserProfiles/IGenderService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserProfiles/INationalityService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserProfiles/IReligionService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserProfiles/IUserService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserProfiles/IWorkService.cs
  EPlast/EPlast.BussinessLayer/Services/AccountService.cs
  EPlast/EPlast.BussinessLayer/Services/AdminService.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityAdministrationService.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityService.cs
  EPlast/EPlast.BussinessLayer/Services/UserManagerService.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/DegreeService.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/EducationService.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/GenderService.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/NationalityService.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/ReligionService.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/UserService.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/WorkService.cs
  EPlast/EPlast.XUnitTest/AccountControllerTests.cs
  EPlast/EPlast.XUnitTest/AdminControllerTests.cs
  EPlast/EPlast.XUnitTest/Controllers/AccountControllerTestsIdentity.cs
  EPlast/EPlast.XUnitTest/Services/AccountServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/UserServiceTests.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Controllers/AdminController.cs
  EPlast/EPlast/Controllers/CItyController.cs
  EPlast/EPlast/Controllers/DocumentationController.cs
  EPlast/EPlast/Mapping/DegreeProfile.cs
  EPlast/EPlast/Mapping/EducationProfile.cs
  EPlast/EPlast/Mapping/GenderProfile.cs
  EPlast/EPlast/Mapping/NationalityProfile.cs
  EPlast/EPlast/Mapping/ReligionProfile.cs
  EPlast/EPlast/Mapping/UserProfile.cs
  EPlast/EPlast/Mapping/UserProfileProfile.cs
  EPlast/EPlast/Mapping/WorkProfile.cs
  EPlast/EPlast/Startup.cs
Labels: Configuration

#37 Added xUnit tests to DocumentationController decision methods.
  EPlast/EPlast.XUnitTest/DocumentationControllerDecisionTests.cs
  EPlast/EPlast/Controllers/DocumentationController.cs
Labels: Configuration
