Repository ita-social-projects/EPlast, pull requests merged in 2020-06, with the labels that each got.

#49 Ab refactoring
  EPlast/EPlast.BussinessLayer/Interfaces/AnnualReport/IAnnualReportService.cs
  EPlast/EPlast.BussinessLayer/Services/AnnualReport/AnnualReportService.cs
  EPlast/EPlast.DataAccess/Repositories/Interfaces/Base/IRepositoryBase.cs
  EPlast/EPlast.DataAccess/Repositories/Interfaces/Base/IRepositoryWrapper.cs
  EPlast/EPlast.DataAccess/Repositories/Realizations/Base/RepositoryBase.cs
  EPlast/EPlast.DataAccess/Repositories/Realizations/Base/RepositoryWrapper.cs
  EPlast/EPlast/Controllers/DocumentationController.cs
Labels: Status: Review Needed

#52 OV city controller and services tests
  EPlast/EPlast.XUnitTest/Controllers/CityControllerTests.cs
  EPlast/EPlast.XUnitTest/Services/City/CityServiceTests.cs
Labels: Configuration

#56 Mk master blanks
  EPlast/EPlast.BussinessLayer/Interfaces/FileManager/IFileStreamManager.cs
  EPlast/EPlast.BussinessLayer/Interfaces/PDF/IPDFCreator.cs
  EPlast/EPlast.BussinessLayer/Interfaces/PDF/IPDFDocument.cs
  EPlast/EPlast.BussinessLayer/Interfaces/PDF/IPDFService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/PDF/IPDFSettings.cs
  EPlast/EPlast.BussinessLayer/Models/BlankModel.cs
  EPlast/EPlast.BussinessLayer/Services/Decision/DecisionService.cs
  EPlast/EPlast.BussinessLayer/Services/FileManager/FileStreamManager.cs
  EPlast/EPlast.BussinessLayer/Services/PDF/Documents/BlankDocument.cs
  EPlast/EPlast.BussinessLayer/Services/PDF/Documents/DecisionDocument.cs
  EPlast/EPlast.BussinessLayer/Services/PDF/Documents/PdfDocument.cs
  EPlast/EPlast.BussinessLayer/Services/PDF/PDFCreator.cs
  EPlast/EPlast.BussinessLayer/Services/PDF/PDFService.cs
  EPlast/EPlast.BussinessLayer/Services/PDF/PDFSettings.cs
  EPlast/EPlast/Controllers/DocumentationController.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/wwwroot/images/pdf/Header-Eplast-Blank.png
  EPlast/EPlast/wwwroot/images/pdf/Statement-photo.png
  EPlast/EPlast/wwwroot/uncompiled/ts/UserProfile.js
Labels: Type: Maintenances, enhancement

#55 OV fixing sonar bugs
  EPlast/EPlast.BussinessLayer/Services/Admin/AdminService.cs
  EPlast/EPlast.BussinessLayer/Services/Decision/DecisionService.cs
  EPlast/EPlast.XUnitTest/Controllers/CityControllerTests.cs
  EPlast/EPlast.XUnitTest/Controllers/DocumentationControllerDecisionTests.cs
  EPlast/EPlast.XUnitTest/Services/City/CityServiceTests.cs
Labels: Configuration, bug

#58 Ab refactoring
  EPlast/EPlast.BussinessLayer/Interfaces/AnnualReport/IAnnualReportService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/City/ICityMembersService.cs
  EPlast/EPlast.BussinessLayer/Services/AnnualReport/AnnualReportService.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityMembersService.cs
  EPlast/EPlast.XUnitTest/Controllers/AnnualReportControllerTests.cs
  EPlast/EPlast.XUnitTest/Controllers/DocumentationControllerAnnualReportTests.cs
  EPlast/EPlast.XUnitTest/Controllers/DocumentationControllerDecisionTests.cs
  EPlast/EPlast/Controllers/AnnualReportController.cs
  EPlast/EPlast/Controllers/DocumentationController.cs
  EPlast/EPlast/Views/AnnualReport/CreateEditAsync.cshtml
  EPlast/EPlast/Views/AnnualReport/GetAllAsync.cshtml
  EPlast/EPlast/Views/AnnualReport/_Get.cshtml
  EPlast/EPlast/Views/Shared/_Layout.cshtml
  EPlast/EPlast/wwwroot/uncompiled/ts/annualReport.js
  EPlast/EPlast/wwwroot/uncompiled/ts/annualReport.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/annualReport.ts
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/mainMenu.ts
Labels: Status: Review Needed

#54 VV Sonar bugs
  EPlast/EPlast.BussinessLayer/Services/City/CityService.cs
  EPlast/EPlast.BussinessLayer/Services/ConfirmedUsers/ConfirmedUsersService.cs
  EPlast/EPlast.BussinessLayer/Services/Events/EventGalleryManager.cs
  EPlast/EPlast.BussinessLayer/Services/UserManager/UserManagerService.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/UserService.cs
  EPlast/EPlast.XUnitTest/Services/UserProfiles/DegreeServiceTest.cs
  EPlast/EPlast.XUnitTest/Services/UserProfiles/EducationServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/UserProfiles/GenderServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/UserProfiles/NationalityServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/UserProfiles/ReligionServiceTest.cs
  EPlast/EPlast.XUnitTest/Services/UserProfiles/WorkServiceTests.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Views/Shared/_Layout.cshtml
Labels: enhancement

#60 Br refactoring
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/UserDTO.cs
  EPlast/EPlast.BussinessLayer/Interfaces/Events/IEventAdminManager.cs
  EPlast/EPlast.BussinessLayer/Interfaces/Events/IParticipantManager.cs
  EPlast/EPlast.BussinessLayer/Mapping/EventUser/EventGeneralInfoProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/EventUser/EventProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/EventUser/EventTypeProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/Events/EventAdminProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/Events/EventGalleryProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/Events/EventInfoProfile.cs
  EPlast/EPlast.BussinessLayer/Services/EventUser/EventUserManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/ActionManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/EventAdminManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/EventGalleryManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/ParticipantManager.cs
  EPlast/EPlast.DataAccess/EPlastDBContext.cs
  EPlast/EPlast.DataAccess/Entities/Event/Event.cs
  EPlast/EPlast.DataAccess/Entities/Event/EventAdmin.cs
  EPlast/EPlast.DataAccess/Entities/Event/EventAdministration.cs
  EPlast/EPlast.DataAccess/Entities/Event/EventCategory.cs
  EPlast/EPlast.DataAccess/Entities/Event/EventGallary.cs
  EPlast/EPlast.DataAccess/Entities/Event/EventStatus.cs
  EPlast/EPlast.DataAccess/Entities/Event/EventType.cs
  EPlast/EPlast.DataAccess/Entities/Event/Gallary.cs
  EPlast/EPlast.DataAccess/Entities/User/Participant.cs
  EPlast/EPlast.DataAccess/Entities/User/User.cs
  EPlast/EPlast.DataAccess/Repositories/Interfaces/Events/IEventAdminRepository.cs
  EPlast/EPlast.DataAccess/Repositories/Interfaces/Events/IEventAdministrationRepository.cs
  EPlast/EPlast.DataAccess/Repositories/Interfaces/Events/IEventCategoryRepository.cs
  EPlast/EPlast.DataAccess/Repositories/Interfaces/Events/IEventGallaryRepository.cs
  EPlast/EPlast.DataAccess/Repositories/Interfaces/Events/IEventRepository.cs
  EPlast/EPlast.DataAccess/Repositories/Interfaces/Events/IEventStatusRepository.cs
  EPlast/EPlast.DataAccess/Repositories/Interfaces/Events/IEventTypeRepository.cs
  EPlast/EPlast.DataAccess/Repositories/Interfaces/Events/IGallaryRepository.cs
  EPlast/EPlast.DataAccess/Repositories/Realizations/Events/EventAdminRepository.cs
  EPlast/EPlast.DataAccess/Repositories/Realizations/Events/EventAdministrationRepository.cs
  EPlast/EPlast.DataAccess/Repositories/Realizations/Events/EventCategoryRepository.cs
  EPlast/EPlast.DataAccess/Repositories/Realizations/Events/EventGallaryRepository.cs
  EPlast/EPlast.DataAccess/Repositories/Realizations/Events/EventRepository.cs
  EPlast/EPlast.DataAccess/Repositories/Realizations/Events/EventStatusRepository.cs
  EPlast/EPlast.DataAccess/Repositories/Realizations/Events/EventTypeRepository.cs
  EPlast/EPlast.DataAccess/Repositories/Realizations/Events/GallaryRepository.cs
  EPlast/EPlast.XUnitTest/Services/Events/ActionManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventCategoryManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventGalleryManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventStatusManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventTypeManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/ParticipantManagerTests.cs
  EPlast/EPlast/Models/ViewModelInitializations/CreateEventVMInitializer.cs
  EPlast/EPlast/Models/ViewModelInitializations/Interfaces/ICreateEventVMInitializer.cs
  EPlast/EPlast/ViewModels/UserProfile/UserViewModel.cs
Labels: Type: Maintenances, enhancement

#64 Mk master decision fix
  EPlast/EPlast.BussinessLayer/Interfaces/Decesion/IDecisionService.cs
  EPlast/EPlast.BussinessLayer/Services/Decision/DecisionService.cs
  EPlast/EPlast.XUnitTest/Controllers/DecisionControllerTests.cs
  EPlast/EPlast.XUnitTest/Services/DecisionServiceTests.cs
  EPlast/EPlast/Controllers/DecisionController.cs
  EPlast/EPlast/EPlast.csproj
  EPlast/EPlast/Views/Decision/ReadDecision.cshtml
  EPlast/EPlast/Views/Decision/_CreateDecision.cshtml
  EPlast/EPlast/Views/Decision/_DeleteDecision.cshtml
  EPlast/EPlast/Views/Decision/_EditDecision.cshtml
  EPlast/EPlast/Views/Documentation/index.cshtml
  EPlast/EPlast/Views/Shared/_Layout.cshtml
  EPlast/EPlast/wwwroot/uncompiled/ts/decision.js
  EPlast/EPlast/wwwroot/uncompiled/ts/decision.js.map
  EPlast/EPlast/wwwroot/uncompiled/ts/decision.ts
Labels: Type: Maintenances

#63 Os event user controller tests
  EPlast/EPlast.BussinessLayer/DTO/EventUser/EventCreateDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/EventUser/EventCreationDTO.cs
  EPlast/EPlast.BussinessLayer/Interfaces/EventUser/IEventUserManager.cs
  EPlast/EPlast.BussinessLayer/Mapping/EventUser/EventProfile.cs
  EPlast/EPlast.BussinessLayer/Services/EventUser/EventUserManager.cs
  EPlast/EPlast.XUnitTest/Controllers/EventUserControllerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventAdminManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventUserManagerTests.cs
  EPlast/EPlast/Controllers/EventUserController.cs
  EPlast/EPlast/Mapping/EventUser/EventProfile.cs
  EPlast/EPlast/ViewModels/EventUser/EventCreateViewModel.cs
  EPlast/EPlast/ViewModels/EventUser/EventCreationViewModel.cs
  EPlast/EPlast/Views/Action/EventInfo.cshtml
  EPlast/EPlast/Views/Action/Events.cshtml
  EPlast/EPlast/Views/EventUser/EventEdit.cshtml
  EPlast/EPlast/Views/EventUser/EventUser.cshtml
  EPlast/EPlast/Views/EventUser/SetAdministration.cshtml
Labels: Type: Maintenances, enhancement

#61 OV sonar code coverage
  EPlast/EPlast.BussinessLayer/Services/City/CityService.cs
  EPlast/EPlast.XUnitTest/Controllers/CityControllerTests.cs
  EPlast/EPlast.XUnitTest/Services/City/CityServiceTests.cs
  EPlast/EPlast/Controllers/CItyController.cs
Labels: Configuration, bug

#62 Id tests for home and account services
  EPlast/EPlast.XUnitTest/Services/Authentication/AccountServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/HomeServiceTests.cs
Labels: Configuration, enhancement

#67 AS-Fixed Some Problems in Account Service
  EPlast/EPlast.BussinessLayer/Services/AccountAuthentication/AccountService.cs
Labels: Status: In Progress, Status: Review Needed

#75 Async repositories
  EPlast/EPlast.DataAccess/Repositories/Interfaces/Base/IRepositoryBase.cs
  EPlast/EPlast.DataAccess/Repositories/Realizations/Base/RepositoryBase.cs
Labels: Status: Completed

#78 Vv rewrite to async
  EPlast/EPlast.BussinessLayer/Interfaces/Admin/IAdminService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/City/ICItyAdministrationService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/City/ICityService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/ConfirmedUsers/IConfirmedUsersService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserManager/IUserManagerService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserProfiles/IDegreeService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserProfiles/IEducationService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserProfiles/IGenderService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserProfiles/INationalityService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserProfiles/IReligionService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserProfiles/IUserService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserProfiles/IWorkService.cs
  EPlast/EPlast.BussinessLayer/Services/Admin/AdminService.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityAdministrationService.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityService.cs
  EPlast/EPlast.BussinessLayer/Services/ConfirmedUsers/ConfirmedUsersService.cs
  EPlast/EPlast.BussinessLayer/Services/UserManager/UserManagerService.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/DegreeService.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/EducationService.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/GenderService.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/NationalityService.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/ReligionService.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/UserService.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/WorkService.cs
  EPlast/EPlast.XUnitTest/Controllers/AccountControllerTests.cs
  EPlast/EPlast.XUnitTest/Controllers/AdminControllerTests.cs
  EPlast/EPlast.XUnitTest/Controllers/CityControllerTests.cs
  EPlast/EPlast.XUnitTest/Services/City/CityServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/UserArea/ConfirmedUsersServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/UserArea/UserServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/UserProfiles/DegreeServiceTest.cs
  EPlast/EPlast.XUnitTest/Services/UserProfiles/EducationServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/UserProfiles/GenderServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/UserProfiles/NationalityServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/UserProfiles/ReligionServiceTest.cs
  EPlast/EPlast.XUnitTest/Services/UserProfiles/WorkServiceTests.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Controllers/AdminController.cs
  EPlast/EPlast/Controllers/CItyController.cs
  EPlast/EPlast/Controllers/ClubController.cs
  EPlast/EPlast/Views/Account/Approvers.cshtml
  EPlast/EPlast/Views/Admin/UsersTable.cshtml
  EPlast/EPlast/Views/City/Index.cshtml
Labels: Configuration

#82 Br rewrite to async
  EPlast/EPlast.BussinessLayer/Interfaces/EventUser/IEventUserManager.cs
  EPlast/EPlast.BussinessLayer/Interfaces/Events/IActionManager.cs
  EPlast/EPlast.BussinessLayer/Interfaces/Events/IEventAdminManager.cs
  EPlast/EPlast.BussinessLayer/Interfaces/Events/IEventCategoryManager.cs
  EPlast/EPlast.BussinessLayer/Interfaces/Events/IEventGalleryManager.cs
  EPlast/EPlast.BussinessLayer/Interfaces/Events/IEventStatusManager.cs
  EPlast/EPlast.BussinessLayer/Interfaces/Events/IEventTypeManager.cs
  EPlast/EPlast.BussinessLayer/Interfaces/Events/IParticipantManager.cs
  EPlast/EPlast.BussinessLayer/Interfaces/Events/IParticipantStatusManager.cs
  EPlast/EPlast.BussinessLayer/Mapping/EventUser/EventAdministrationEditProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/EventUser/EventEditAdminProfile.cs
  EPlast/EPlast.BussinessLayer/Services/EventUser/EventUserManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/ActionManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/EventAdminManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/EventCategoryManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/EventGalleryManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/EventStatusManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/EventTypeManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/ParticipantManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/ParticipantStatusManager.cs
  EPlast/EPlast.DataAccess/Entities/Event/EventAdmin.cs
  EPlast/EPlast.DataAccess/Entities/Event/EventAdministration.cs
  EPlast/EPlast.DataAccess/Entities/Event/EventCategory.cs
  EPlast/EPlast.XUnitTest/Controllers/ActionControllerTests.cs
  EPlast/EPlast.XUnitTest/Controllers/EventUserControllerTests.cs
  EPlast/EPlast.XUnitTest/EPlast.XUnitTest.csproj
  EPlast/EPlast.XUnitTest/Services/Events/ActionManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventAdminManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventCategoryManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventGalleryManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventStatusManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventTypeManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventUserManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/ParticipantManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/ParticipantStatusManagerTests.cs
  EPlast/EPlast/Controllers/ActionController.cs
  EPlast/EPlast/Controllers/EventUserController.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/Views/EventUser/EventCreate.cshtml
Labels: Status: Completed, Type: Maintenances, enhancement

#79 OV rewrite decisions to async
  EPlast/EPlast.BussinessLayer/Interfaces/Decesion/IDecisionService.cs
  EPlast/EPlast.BussinessLayer/Services/Decision/DecisionService.cs
  EPlast/EPlast.XUnitTest/Controllers/DecisionControllerTests.cs
  EPlast/EPlast.XUnitTest/Services/DecisionServiceTests.cs
  EPlast/EPlast/Controllers/DecisionController.cs
Labels: Configuration

#84 Code refactoring
  EPlast/EPlast.BussinessLayer/Interfaces/City/ICItyAdministrationService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/City/ICityService.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityAdministrationService.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityMembersService.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityService.cs
  EPlast/EPlast.XUnitTest/Controllers/AnnualReportControllerTests.cs
  EPlast/EPlast.XUnitTest/Controllers/CityControllerTests.cs
  EPlast/EPlast.XUnitTest/Services/City/CityAdministrationServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/City/CityMembersServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/City/CityServiceTests.cs
  EPlast/EPlast/Controllers/AnnualReportController.cs
  EPlast/EPlast/Controllers/CItyController.cs
Labels: Status: Completed

#86 AS-Add Web Api Controller
  EPlast/EPlast.BussinessLayer/DTO/UserAuthentication/ChangePasswordDto.cs
  EPlast/EPlast.BussinessLayer/DTO/UserAuthentication/ContactsDto.cs
  EPlast/EPlast.BussinessLayer/DTO/UserAuthentication/ForgotPasswordDto.cs
  EPlast/EPlast.BussinessLayer/DTO/UserAuthentication/LoginDto.cs
  EPlast/EPlast.BussinessLayer/DTO/UserAuthentication/RegisterDto.cs
  EPlast/EPlast.BussinessLayer/DTO/UserAuthentication/ResetPasswordDto.cs
  EPlast/EPlast.BussinessLayer/EPlast.BussinessLayer.csproj
  EPlast/EPlast.BussinessLayer/Services/AccountAuthentication/AccountService.cs
  EPlast/EPlast.WebApi/Controllers/AccountController.cs
  EPlast/EPlast.WebApi/Controllers/ValuesController.cs
  EPlast/EPlast.WebApi/EPlast.WebApi.csproj
  EPlast/EPlast.WebApi/Program.cs
  EPlast/EPlast.WebApi/Properties/launchSettings.json
  EPlast/EPlast.WebApi/Startup.cs
  EPlast/EPlast.WebApi/appsettings.json
  EPlast/EPlast.XUnitTest/Services/Authentication/AccountServiceTests.cs
  EPlast/EPlast/Controllers/AccountController.cs
Labels: Configuration, Status: Accepted

#88 AS-Test Account Controller Web Api
  EPlast/EPlast.BussinessLayer/Mapping/UserMapping/UserMappingProfile.cs
  EPlast/EPlast.BussinessLayer/Services/AccountAuthentication/AccountService.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/Approver.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/ConfirmedUser.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/Degree.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/Education.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/Gender.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/Nationality.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/Participant.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/ParticipantStatus.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/Religion.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/User.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/UserPlastDegree.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/UserPlastDegreeType.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/UserProfile.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/Work.cs
  EPlast/EPlast.WebApi/Controllers/AccountController.cs
  EPlast/EPlast.WebApi/Startup.cs
Labels: Configuration, Status: Accepted

#89 Br web api version
  EPlast/EPlast.BussinessLayer/Mapping/EventUser/EventGeneralInfoProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/EventUser/EventProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/EventUser/EventTypeProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/Events/EventAdminProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/Events/EventGalleryProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/Events/EventInfoProfile.cs
  EPlast/EPlast.WebApi/Controllers/EventsController.cs
  EPlast/EPlast.WebApi/EPlast.WebApi.csproj
Labels: enhancement

#90 OV decisions web api controller
  EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
  EPlast/EPlast.WebApi/Models/Decision/DecisionViewModel.cs
Labels: Configuration, enhancement

#91 Web api controllers
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/DegreeDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/EducationDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/GenderDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/NationalityDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/ReligionDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/UserDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/UserProfileDTO.cs
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/WorkDTO.cs
  EPlast/EPlast.BussinessLayer/Mapping/Approver/ApproveProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/ConfirmedUser/ConfirmedUserProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/User/UserMappingProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/UserProfile/DegreeProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/UserProfile/EducationProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/UserProfile/GenderProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/UserProfile/NationalityProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/UserProfile/ReligionProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/UserProfile/UserProfileProfile.cs
  EPlast/EPlast.BussinessLayer/Mapping/UserProfile/WorkProfile.cs
  EPlast/EPlast.WebApi/Controllers/AdminController.cs
  EPlast/EPlast.WebApi/Controllers/UserController.cs
  EPlast/EPlast.WebApi/Models/Admin/CitiesAdminsViewModel.cs
  EPlast/EPlast.WebApi/Models/Role/RoleViewModel.cs
  EPlast/EPlast.WebApi/Models/User/EditUserViewModel.cs
  EPlast/EPlast.WebApi/Models/User/PersonalDataViewModel.cs
  EPlast/EPlast.WebApi/Models/User/UserEducationViewModel.cs
  EPlast/EPlast.WebApi/Models/User/UserWorkViewModel.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/ViewModels/UserProfile/UserProfileViewModel.cs
Labels: Configuration

#94 OV master cities web api controller
  EPlast/EPlast.BussinessLayer/DTO/City/CityDTO.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityService.cs
  EPlast/EPlast.WebApi/Controllers/CitiesController.cs
  EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
  EPlast/EPlast/Controllers/CItyController.cs
Labels: Configuration, enhancement

#95 OV refactoring api controller
  EPlast/EPlast.BussinessLayer/Interfaces/City/ICityService.cs
  EPlast/EPlast.BussinessLayer/Services/City/CityService.cs
  EPlast/EPlast.WebApi/Controllers/CitiesController.cs
  EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
  EPlast/EPlast.XUnitTest/Controllers/CityControllerTests.cs
  EPlast/EPlast.XUnitTest/Services/City/CityServiceTests.cs
  EPlast/EPlast/Controllers/CItyController.cs
Labels: Configuration

#98 Fix users table after deploy
  EPlast/EPlast.BussinessLayer/Services/Admin/AdminService.cs
Labels: Configuration, enhancement

#102 Update DataTable.scss
  EPlast/EPlast/wwwroot/uncompiled/sass/DataTable.scss
Labels: enhancement

#104 Br global error handling
  EPlast/EPlast.BussinessLayer/Interfaces/Logging/IGlobalLoggerService.cs
  EPlast/EPlast.BussinessLayer/Interfaces/Logging/ILoggerService.cs
  EPlast/EPlast.BussinessLayer/Services/Decision/DecisionService.cs
  EPlast/EPlast.BussinessLayer/Services/Events/ActionManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/EventGalleryManager.cs
  EPlast/EPlast.BussinessLayer/Services/Events/ParticipantManager.cs
  EPlast/EPlast.BussinessLayer/Services/Logging/GlobalLoggerService.cs
  EPlast/EPlast.BussinessLayer/Services/Logging/LoggerService.cs
  EPlast/EPlast.BussinessLayer/Services/PDF/PDFService.cs
  EPlast/EPlast.WebApi/Controllers/AccountController.cs
  EPlast/EPlast.WebApi/Controllers/AnnualReportController.cs
  EPlast/EPlast.WebApi/Controllers/CitiesController.cs
  EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
  EPlast/EPlast.WebApi/Controllers/EventsController.cs
  EPlast/EPlast.WebApi/Controllers/UserController.cs
  EPlast/EPlast.WebApi/CustomExceptionMiddleware/ExceptionMiddleware.cs
  EPlast/EPlast.WebApi/EPlast.WebApi.csproj
  EPlast/EPlast.WebApi/Extensions/ExceptionMiddlewareExtensions.cs
  EPlast/EPlast.WebApi/Models/ErrorHandling/ErrorDetails.cs
  EPlast/EPlast.WebApi/Program.cs
  EPlast/EPlast.WebApi/Properties/launchSettings.json
  EPlast/EPlast.WebApi/Startup.cs
  EPlast/EPlast.WebApi/appsettings.json
  EPlast/EPlast.WebApi/nlog.config
  EPlast/EPlast.XUnitTest/Controllers/AccountControllerTests.cs
  EPlast/EPlast.XUnitTest/Controllers/AnnualReportControllerTests.cs
  EPlast/EPlast.XUnitTest/Controllers/CityControllerTests.cs
  EPlast/EPlast.XUnitTest/Controllers/ClubControllerTests.cs
  EPlast/EPlast.XUnitTest/Controllers/DecisionControllerTests.cs
  EPlast/EPlast.XUnitTest/Services/DecisionServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/ActionManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventGalleryManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/ParticipantManagerTests.cs
  EPlast/EPlast/Controllers/AccountController.cs
  EPlast/EPlast/Controllers/AnnualReportController.cs
  EPlast/EPlast/Controllers/CItyController.cs
  EPlast/EPlast/Controllers/ClubController.cs
  EPlast/EPlast/Controllers/DecisionController.cs
  EPlast/EPlast/Startup.cs
Labels: Status: Review Needed, Type: Enhancement

#106 VV azure blob storage
  EPlast/EPlast.BussinessLayer/DTO/UserProfiles/UserDTO.cs
  EPlast/EPlast.BussinessLayer/EPlast.BussinessLayer.csproj
  EPlast/EPlast.BussinessLayer/Interfaces/AzureStorage/Base/IAzureBlobConnectionFactory.cs
  EPlast/EPlast.BussinessLayer/Interfaces/AzureStorage/Base/IBlobStorageRepository.cs
  EPlast/EPlast.BussinessLayer/Interfaces/AzureStorage/IUserBlobStorageRepository.cs
  EPlast/EPlast.BussinessLayer/Interfaces/UserProfiles/IUserService.cs
  EPlast/EPlast.BussinessLayer/Services/AzureStorage/Base/AzureBlobConnectionFactory.cs
  EPlast/EPlast.BussinessLayer/Services/AzureStorage/Base/BlobStorageRepository.cs
  EPlast/EPlast.BussinessLayer/Services/AzureStorage/UserBlobStorageRepository.cs
  EPlast/EPlast.BussinessLayer/Services/UserProfiles/UserService.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/User.cs
  EPlast/EPlast.WebApi/Controllers/UserController.cs
  EPlast/EPlast.WebApi/Startup.cs
  EPlast/EPlast.WebApi/appsettings.json
  EPlast/EPlast.XUnitTest/Services/UserArea/UserServiceTests.cs
  EPlast/EPlast/Startup.cs
Labels: Configuration

#111 AS fix some problems
  EPlast/EPlast.BLL/Interfaces/AccountAuthentication/IAccountService.cs
  EPlast/EPlast.BLL/Models/Jwt/AppSettings.cs
  EPlast/EPlast.BLL/Models/Jwt/AuthenticateRequest.cs
  EPlast/EPlast.BLL/Models/Jwt/AuthenticateResponse.cs
  EPlast/EPlast.BLL/Models/Jwt/LoginModel.cs
  EPlast/EPlast.BLL/Services/AccountAuthentication/AccountService.cs
  EPlast/EPlast.WebApi/Controllers/AccountController.cs
  EPlast/EPlast.WebApi/EPlast.WebApi.csproj
  EPlast/EPlast.WebApi/Startup.cs
  EPlast/EPlast.WebApi/appsettings.json
Labels: bug

#115 added cors
  EPlast/EPlast.WebApi/EPlast.WebApi.csproj
  EPlast/EPlast.WebApi/Startup.cs
Labels: Configuration
