Repository ita-social-projects/EPlast, pull requests merged in 2020-08, with the labels that each got.

#218 Fixed some problems
  EPlast/EPlast.WebApi/Controllers/AuthController.cs
Labels: enhancement

#230 Br rewriting to blobs
  EPlast/EPlast.BLL/DTO/Events/EventInfoDTO.cs
  EPlast/EPlast.BLL/Interfaces/AzureStorage/IEventBlobStorageRepository.cs
  EPlast/EPlast.BLL/Interfaces/Events/IActionManager.cs
  EPlast/EPlast.BLL/Interfaces/Events/IEventGalleryManager.cs
  EPlast/EPlast.BLL/Mapping/Events/EventInfoProfile.cs
  EPlast/EPlast.BLL/Services/AzureStorage/EventBlobStorageRepository.cs
  EPlast/EPlast.BLL/Services/Events/ActionManager.cs
  EPlast/EPlast.BLL/Services/Events/EventGalleryManager.cs
  EPlast/EPlast.WebApi/Controllers/EventsController.cs
  EPlast/EPlast.WebApi/Startup.cs
  EPlast/EPlast.WebApi/appsettings.json
  EPlast/EPlast.XUnitTest/Controllers/ActionControllerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/ActionManagerTests.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventGalleryManagerTests.cs
  EPlast/EPlast/Controllers/ActionController.cs
  EPlast/EPlast/Startup.cs
  EPlast/EPlast/appsettings.json
Labels: enhancement

#227 Task#186 Added Unit tests for UserConroller
  EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
Labels: Status: Review Needed

#228 Task#184 Added Unit tests for EventsUsersConroller
  EPlast/EPlast.Tests/Controllers/EventsUsersControllerTests.cs
Labels: Status: Review Needed

#250 Bug
  EPlast/EPlast.BLL/ExtensionMethods/EnumExtensions.cs
  EPlast/EPlast.BLL/Services/AnnualReport/AnnualReportService.cs
Labels: bug

#232 Added unit tests for some methods in EventsController
  EPlast/EPlast.Tests/Controllers/EventsControllerTests.cs
Labels: Status: Review Needed

#233 UnitTests EventCallendarController, DecisionsController. Refactroring ClubController
  EPlast/EPlast.Tests/Controllers/DecisionsControllerTests.cs
  EPlast/EPlast.Tests/Controllers/EventCalendarControllerTests.cs
  EPlast/EPlast.WebApi/Controllers/ClubController.cs
Labels: Status: Review Needed

#259 Added UnitTests for ClubController
  EPlast/EPlast.Tests/Controllers/ClubControllerTests.cs
Labels: Status: Review Needed

#261 Fixed problem with registration
  EPlast/EPlast.BLL/Services/Auth/AuthService.cs
  EPlast/EPlast.WebApi/Controllers/AuthController.cs
Labels: bug

#264 Added Dockerfile
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: Configuration

#273 Fix some bugs
  EPlast/EPlast.BLL/Services/UserProfiles/UserService.cs
  EPlast/EPlast.WebApi/Controllers/UserController.cs
  EPlast/EPlast.XUnitTest/Services/UserArea/UserServiceTests.cs
Labels: enhancement

#288 add authentication roles for Decisions
  EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
  EPlast/EPlast.WebApi/Mapping/Decision/DecisionProfile.cs
Labels: Configuration

#294 Decisions refactoring
  EPlast/EPlast.BLL/Interfaces/Decesion/IDecisionService.cs
  EPlast/EPlast.BLL/Services/Decision/DecisionService.cs
  EPlast/EPlast.Tests/Controllers/DecisionsControllerTests.cs
  EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
  EPlast/EPlast.XUnitTest/Controllers/DecisionControllerTests.cs
  EPlast/EPlast.XUnitTest/Services/Decision/DecisionServiceTests.cs
  EPlast/EPlast/Controllers/DecisionController.cs
Labels: Configuration

#308 Active membership controller
  EPlast/EPlast.BLL/DTO/ActiveMembership/UserPlastDegreeDTO.cs
  EPlast/EPlast.BLL/Services/ActiveMembership/PlastDegreeService.cs
  EPlast/EPlast.Tests/Services/ActiveMembership/AccessLevelServiceTests.cs
  EPlast/EPlast.Tests/Services/ActiveMembership/PlastDegreeServiceTests.cs
  EPlast/EPlast.WebApi/Controllers/ActiveMembershipController.cs
  EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
Labels: Configuration, bug

#320 Create LICENSE
  LICENSE
Labels: documentation
