Repository ita-social-projects/EPlast, pull requests merged in 2021-02, with the labels that each got.

#834 Added ResendEmailRegistr
  EPlast/EPlast.Resources/AuthenticationErrors.uk.resx
  EPlast/EPlast.Tests/Controllers/AuthControllerTests.cs
  EPlast/EPlast.WebApi/Controllers/AdminController.cs
  EPlast/EPlast.WebApi/Controllers/AuthController.cs
Labels: Users Table (Таблиця користувачів)

#837 FixCodeSmells
  EPlast/EPlast.BLL/Services/Precautions/UserPrecautionService.cs
Labels: Precaution

#848 FixFilter
  EPlast/EPlast.BLL/Services/Precautions/UserPrecautionService.cs
Labels: Precaution

#853 FixTests
  EPlast/EPlast.BLL/Services/Precautions/PrecautionService.cs
Labels: Precaution

#856 Fixtests
  EPlast/EPlast.BLL/Services/Decision/DecisionService.cs
  EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
  EPlast/EPlast.XUnitTest/Services/Decision/DecisionServiceTests.cs
Labels: Decisions (Рішення)

#864 Fixed reminder text
  EPlast/EPlast.BLL/Services/Auth/AuthEmailService.cs
Labels: Cities (станиці)

#874 City approve email notification
  EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
  EPlast/EPlast.DataAccess/Repositories/Interfaces/Base/IRepositoryWrapper.cs
  EPlast/EPlast.DataAccess/Repositories/Realizations/Base/RepositoryWrapper.cs
  EPlast/EPlast.Tests/Services/City/CityParticipantsServiceTests.cs
  EPlast/EPlast.WebApi/appsettings.json
Labels: Cities (станиці)

#875 Removed wrong dependencies
  EPlast/EPlast.Tests/EPlast.Tests.csproj
  EPlast/EPlast.WebApi/EPlast.WebApi.csproj
  EPlast/EPlast.WebApi/Startup.cs
  EPlast/EPlast.WebApi/StartupExtensions/AddServicesExtension.cs
Labels: Improvement

#879 Added email sending
  EPlast/EPlast.BLL/Interfaces/ConfirmedUsers/IConfirmedUsersService.cs
  EPlast/EPlast.BLL/Services/ConfirmedUsers/ConfirmedUsersService.cs
  EPlast/EPlast.DataAccess/EPlastDBContext.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/User.cs
  EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
  EPlast/EPlast.Tests/Services/Club/ClubServiceTests.cs
  EPlast/EPlast.WebApi/Controllers/UserController.cs
  EPlast/EPlast.WebApi/EPlast.WebApi.csproj
  EPlast/EPlast.XUnitTest/Services/Club/ClubServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/UserArea/ConfirmedUsersServiceTests.cs
Labels: Delegation (Поручення)

#885 User vauching email notification
  EPlast/EPlast.BLL/Services/ConfirmedUsers/ConfirmedUsersService.cs
Labels: Notifications(Сповіщення)

#889 Added email notification for probation period ends.
  EPlast/EPlast.BLL/Interfaces/EmailSending/INewPlastMemberEmailGreetingService.cs
  EPlast/EPlast.BLL/Interfaces/UserProfiles/IUserService.cs
  EPlast/EPlast.BLL/Services/EmailSending/NewPlastMemberEmailGreetingService.cs
  EPlast/EPlast.BLL/Services/UserProfiles/UserService.cs
  EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
  EPlast/EPlast.Tests/Services/EmailSending/NewPlastMemberEmailGreetingTests.cs
  EPlast/EPlast.WebApi/Controllers/UserController.cs
  EPlast/EPlast.WebApi/StartupExtensions/AddDependenciesExtension.cs
  EPlast/EPlast.WebApi/StartupExtensions/AddRecurringJobManager.cs
  EPlast/EPlast.XUnitTest/Services/UserArea/UserServiceTests.cs
Labels: Notifications(Сповіщення)
