Repository ita-social-projects/EPlast, pull requests merged in 2021-10, with the labels that each got.

#1839 Restricted possibility to edit profiles via API (Fixed issue #1825)
  EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
  EPlast/EPlast.WebApi/Controllers/UserController.cs
Labels: Bug, Profile

#1854 Fixed removing governing body with admins
  EPlast/EPlast.BLL/Services/GoverningBodies/GoverningBodiesService.cs
  EPlast/EPlast.BLL/Services/GoverningBodies/Sector/SectorService.cs
  EPlast/EPlast.Tests/Services/GoverningBody/GoverningBodiesServiceTests.cs
  EPlast/EPlast.Tests/Services/GoverningBody/Sector/SectorServiceTests.cs
Labels: Bug, Governing Bodies(Керівні Органи), Governing Body's Sectors(Напрями)

#1858 Restricted possibility to add wrong active membership dates via Postman (Fix bug #1843)
  EPlast/EPlast.BLL/DTO/ActiveMembership/UserMembershipDatesDTO.cs
  EPlast/EPlast.Resources/AllowedDates.cs
  EPlast/EPlast.WebApi/Controllers/ActiveMembershipController.cs
Labels: Bug, Active Membership

#1859 Disabled possibility to get precautions using registered user token ( Fix bug #1847 )
  EPlast/EPlast.WebApi/Controllers/PrecautionController.cs
Labels: Bug, Precaution, Рівні доступу (Access Levels)

#1862 Added admingetter for sectors
  EPlast/EPlast.BLL/Interfaces/GoverningBodies/Sector/ISectorService.cs
  EPlast/EPlast.BLL/Services/GoverningBodies/Sector/SectorAdministrationService.cs
  EPlast/EPlast.BLL/Services/GoverningBodies/Sector/SectorService.cs
  EPlast/EPlast.Tests/Controllers/GoverningBodySectorsControllerTests.cs
  EPlast/EPlast.Tests/Services/GoverningBody/Sector/SectorAdministrationServiceTests.cs
  EPlast/EPlast.Tests/Services/GoverningBody/Sector/SectorServiceTests.cs
  EPlast/EPlast.WebApi/Controllers/GoverningBodySectorsController.cs
Labels: Governing Body's Sectors(Напрями)

#1863 Added removing admin previlege before becoming former member
  EPlast/EPlast.BLL/Services/Admin/AdminService.cs
  EPlast/EPlast.Tests/Services/Admin/AdminServiceTests.cs
Labels: Bug, Governing Bodies(Керівні Органи), Governing Body's Sectors(Напрями)

#1875 Add HorizontalPodAutoscaler and configure pod resource limits
  manifests/deployment.yml
  manifests/redis-master-deployment.yaml
Labels: Improvement

#1874 Created custom validator for the birthday date and added validation for phone number ( fix bug #1872)
  EPlast/EPlast.WebApi/CustomAttributes/BitrhdayDateAttribute.cs
  EPlast/EPlast.WebApi/Models/UserModels/UserViewModel.cs
Labels: Bug, Profile

#1899 Changed wrong regular expression for phone number
  EPlast/EPlast.WebApi/Models/UserModels/UserViewModel.cs
Labels: Bug, Profile

#1917 added isActive prop to DTO
  EPlast/EPlast.BLL/DTO/Club/ClubForAdministrationDTO.cs
  EPlast/EPlast.BLL/DTO/Region/RegionForAdministrationDTO.cs
  EPlast/EPlast.Tests/Services/Club/ClubAccess/ClubAccessServiceTest.cs
  EPlast/EPlast.Tests/Services/Regions/RegionAccessServiceTest.cs
Labels: Bug, AnnualReports

#1929 Remove possibility to delete or update hovel or city
  EPlast/EPlast.DataAccess/Repositories/Realizations/Region/RegionRepository.cs
  EPlast/EPlast.Tests/Controllers/ClubControllerTests.cs
  EPlast/EPlast.WebApi/Controllers/ClubController.cs
Labels: Hovels (Курені)

#1934 fix bug #1855
  EPlast/EPlast.BLL/Services/Club/ClubParticipantsService.cs
  EPlast/EPlast.Tests/Services/Club/ClubParticipantsServiceTests.cs
  EPlast/EPlast.WebApi/Controllers/ClubController.cs
Labels: Hovels (Курені)

#1946 fixing bug #1633
  EPlast/EPlast.BLL/Services/Region/RegionService.cs
Labels: Regions (округи)

#1953 The progress bar should not reset when an Adherent changes a City (Fixes bug #1555)
  EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
Labels: Bug, Profile
