Repository ita-social-projects/EPlast, pull requests merged in 2021-05, with the labels that each got.

#1173 Add new role change controller
  EPlast/EPlast.Resources/Roles.cs
  EPlast/EPlast.WebApi/Controllers/ClubController.cs
Labels: Users Table (Таблиця користувачів)

#1199 Fix small bug
  EPlast/EPlast.BLL/DTO/UserProfiles/UserTableDTO.cs
Labels: Users Table (Таблиця користувачів)

#1218 Added club's name of confirmed users and changed some text in applica…
  EPlast/EPlast.BLL/Services/PDF/Documents/BlankDocument.cs
  EPlast/EPlast.BLL/Services/PDF/PDFService.cs
Labels: Type: Bug

#1219 Added web.config to fix GoverningBodies
  EPlast/EPlast.WebApi/web.config
Labels: Governing Bodies(Керівні Органи)

#1227 Various Bug fixes
  EPlast/EPlast.BLL/Services/Admin/AdminService.cs
  EPlast/EPlast.BLL/Services/Precautions/UserPrecautionService.cs
  EPlast/EPlast.Tests/Services/Admin/AdminServiceTests.cs
Labels: Awards (Відзначення), Decisions (Рішення), Events (події), Senior Staff (Кадра виховників)

#1232 New logic for register user
  EPlast/EPlast.BLL/Services/Admin/AdminService.cs
Labels: Users Table (Таблиця користувачів)

#1226 Profiles access levels
  EPlast/EPlast.BLL/DTO/Club/ClubAdministrationDTO.cs
  EPlast/EPlast.BLL/DTO/Club/ClubMembersDTO.cs
  EPlast/EPlast.BLL/Interfaces/City/ICityAccessService.cs
  EPlast/EPlast.BLL/Interfaces/Club/IClubAccessGetter.cs
  EPlast/EPlast.BLL/Interfaces/Club/IClubAccessService.cs
  EPlast/EPlast.BLL/Interfaces/Club/IClubMembers.cs
  EPlast/EPlast.BLL/Interfaces/EventUser/IEventUserManager.cs
  EPlast/EPlast.BLL/Interfaces/UserProfiles/IUserService.cs
  EPlast/EPlast.BLL/Services/AnnualReport/AnnualReportService.cs
  EPlast/EPlast.BLL/Services/City/CityAccess/CityAccessService.cs
  EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
  EPlast/EPlast.BLL/Services/Club/ClubAccess/ClubAccessGetters/ClubAccessForAdminGetter.cs
  EPlast/EPlast.BLL/Services/Club/ClubAccess/ClubAccessGetters/ClubAccessForClubAdminGetter.cs
  EPlast/EPlast.BLL/Services/Club/ClubAccess/ClubAccessService.cs
  EPlast/EPlast.BLL/Services/Club/ClubParticipantsService.cs
  EPlast/EPlast.BLL/Services/Club/ClubService.cs
  EPlast/EPlast.BLL/Services/EducatorsStaff/EducatorsStaffService.cs
  EPlast/EPlast.BLL/Services/UserProfiles/UserService.cs
  EPlast/EPlast.BLL/Settings/CityAccessSettings.cs
  EPlast/EPlast.BLL/Settings/ClubAccessSettings.cs
  EPlast/EPlast.Tests/Controllers/ActiveMembershipControllerTests.cs
  EPlast/EPlast.Tests/Controllers/BlanksControllerTests.cs
  EPlast/EPlast.Tests/Controllers/ClubControllerTests.cs
  EPlast/EPlast.Tests/Controllers/DistinctionControllerTests.cs
  EPlast/EPlast.Tests/Controllers/EventsControllerTests.cs
  EPlast/EPlast.Tests/Controllers/EventsUsersControllerTests.cs
  EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
  EPlast/EPlast.Tests/Services/City/CityParticipantsServiceTests.cs
  EPlast/EPlast.Tests/Services/Club/ClubParticipantsServiceTests.cs
  EPlast/EPlast.Tests/Services/UserProfiles/UserServiceTests.cs
  EPlast/EPlast.WebApi/Controllers/ActiveMembershipController.cs
  EPlast/EPlast.WebApi/Controllers/BlanksController.cs
  EPlast/EPlast.WebApi/Controllers/ClubController.cs
  EPlast/EPlast.WebApi/Controllers/DistinctionController.cs
  EPlast/EPlast.WebApi/Controllers/EventsController.cs
  EPlast/EPlast.WebApi/Controllers/EventsUsersController.cs
  EPlast/EPlast.WebApi/Controllers/RegionsController.cs
  EPlast/EPlast.WebApi/Controllers/UserController.cs
  EPlast/EPlast.WebApi/Mapping/User/UserProfile.cs
  EPlast/EPlast.WebApi/Models/UserModels/UserShortViewModel.cs
  EPlast/EPlast.WebApi/Models/UserModels/UserViewModel.cs
  EPlast/EPlast.XUnitTest/Services/City/CityAccessServiceTests.cs
  EPlast/EPlast.XUnitTest/Services/UserArea/UserServiceTests.cs
Labels: Active Membership, Blank, Profile, Рівні доступу (Access Levels)

#1234 Relocated folder with SecurityModel access files
  EPlast/EPlast.BLL/SecurityModel/SecutityModel.cs
  EPlast/EPlast.WebApi/AccessSecurityModel/GoverningBodyAccessSettings.json
  EPlast/EPlast.WebApi/AccessSecurityModel/RegionsBoardAccessSettings.json
  EPlast/EPlast.WebApi/EPlast.WebApi.csproj
Labels: Governing Bodies(Керівні Органи), Security Model

#1233 ability to view profiles on kvpage
  EPlast/EPlast.WebApi/Controllers/EducatorsStaffController.cs
Labels: Profile, Senior Staff (Кадра виховників), Type: Bug

#1235 Restored missing endpoint in DistinctionController
  EPlast/EPlast.WebApi/Controllers/DistinctionController.cs
Labels: Awards (Відзначення)

#1260 Added prolongation for Region, City and Hovel administrators
  EPlast/EPlast.BLL/Interfaces/City/ICityParticipantsService.cs
  EPlast/EPlast.BLL/Interfaces/Club/IClubParticipantsService.cs
  EPlast/EPlast.BLL/Interfaces/Region/IRegionService.cs
  EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
  EPlast/EPlast.BLL/Services/Club/ClubParticipantsService.cs
  EPlast/EPlast.BLL/Services/Region/RegionAdministrationService.cs
  EPlast/EPlast.BLL/Services/Region/RegionService.cs
  EPlast/EPlast.Tests/Services/City/CityParticipantsServiceTests.cs
  EPlast/EPlast.Tests/Services/Club/ClubParticipantsServiceTests.cs
  EPlast/EPlast.Tests/Services/Regions/RegionAdministrationServiceTests.cs
  EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
  EPlast/EPlast.WebApi/StartupExtensions/AddRecurringJobManager.cs
Labels: Type: Bug
