Repository ita-social-projects/EPlast, pull requests merged in 2022-03, with the labels that each got.

#2351 Changed type of mooney in creating city annual repport
  EPlast/EPlast.BLL/DTO/AnnualReport/AnnualReportDTO.cs
  EPlast/EPlast.DataAccess/Entities/AnnualReport/AnnualReport.cs
Labels: Bug, AnnualReports

#2363 Decision mediator
  EPlast/EPlast.BLL/Commands/Decision/CreateDecisionTargetAsyncCommand.cs
  EPlast/EPlast.BLL/Commands/Decision/DeleteDecisionAsyncCommand.cs
  EPlast/EPlast.BLL/Commands/Decision/SaveDecisionAsyncCommand.cs
  EPlast/EPlast.BLL/Commands/Decision/UpdateCommand.cs
  EPlast/EPlast.BLL/Commands/Decision/UploadFileToBlobAsyncCommand.cs
  EPlast/EPlast.BLL/ExtensionMethods/GetDecisionStatusTypesExtention.cs
  EPlast/EPlast.BLL/Handlers/DecisionHandlers/CreateDecisionTargetAsyncHandler.cs
  EPlast/EPlast.BLL/Handlers/DecisionHandlers/DeleteDecisionAsyncHandler.cs
  EPlast/EPlast.BLL/Handlers/DecisionHandlers/DownloadDecisionFileFromBlobAsyncHandler.cs
  EPlast/EPlast.BLL/Handlers/DecisionHandlers/GetDecisionAsyncHandler.cs
  EPlast/EPlast.BLL/Handlers/DecisionHandlers/GetDecisionListAsyncHandler.cs
  EPlast/EPlast.BLL/Handlers/DecisionHandlers/GetDecisionOrganizationAsyncHandler.cs
  EPlast/EPlast.BLL/Handlers/DecisionHandlers/GetDecisionTargetSearchListAsyncHandler.cs
  EPlast/EPlast.BLL/Handlers/DecisionHandlers/GetDecisionsForTableHandler.cs
  EPlast/EPlast.BLL/Handlers/DecisionHandlers/SaveDecisionAsyncHandler.cs
  EPlast/EPlast.BLL/Handlers/DecisionHandlers/UpdateHandler.cs
  EPlast/EPlast.BLL/Handlers/DecisionHandlers/UploadFileToBlobAsyncHandler.cs
  EPlast/EPlast.BLL/Queries/Decision/DownloadDecisionFileFromBlobAsyncQuery.cs
  EPlast/EPlast.BLL/Queries/Decision/GetDecisionAsyncQuery.cs
  EPlast/EPlast.BLL/Queries/Decision/GetDecisionListAsyncQuery.cs
  EPlast/EPlast.BLL/Queries/Decision/GetDecisionOrganizationAsyncQuery.cs
  EPlast/EPlast.BLL/Queries/Decision/GetDecisionTargetSearchListAsyncQuery.cs
  EPlast/EPlast.BLL/Queries/Decision/GetDecisionsForTableQuery.cs
  EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
  EPlast/EPlast.BLL/Services/Decision/DecisionService.cs
  EPlast/EPlast.BLL/Services/EmailSending/NewPlastMemberEmailGreetingService.cs
  EPlast/EPlast.BLL/Services/Region/RegionService.cs
  EPlast/EPlast.BLL/Services/UserProfiles/UserRenewalService.cs
  EPlast/EPlast.Tests/Controllers/DecisionsControllerTests.cs
  EPlast/EPlast.Tests/ExtentionMethods/GetDecisionStatusTypesExtentionTest.cs
  EPlast/EPlast.Tests/Handlers/Decision/CreateDecisionTargetAsyncHandlerTest.cs
  EPlast/EPlast.Tests/Handlers/Decision/DeleteDecisionAsyncHandlerTest.cs
  EPlast/EPlast.Tests/Handlers/Decision/DownloadDecisionFileFromBlobAsyncHandlerTest.cs
  EPlast/EPlast.Tests/Handlers/Decision/GetDecisionAsyncHandlerTest.cs
  EPlast/EPlast.Tests/Handlers/Decision/GetDecisionListAsyncHandlerTest.cs
  EPlast/EPlast.Tests/Handlers/Decision/GetDecisionOrganizationAsyncHandlerTest.cs
  EPlast/EPlast.Tests/Handlers/Decision/GetDecisionTargetSearchListAsyncHandlerTest.cs
  EPlast/EPlast.Tests/Handlers/Decision/GetDecisionsForTableHandlerTest.cs
  EPlast/EPlast.Tests/Handlers/Decision/SaveDecisionAsyncHandlerTest.cs
  EPlast/EPlast.Tests/Handlers/Decision/UpdateHandlerTest.cs
  EPlast/EPlast.Tests/Handlers/Decision/UploadFileToBlobAsyncHandlerTest.cs
  EPlast/EPlast.Tests/Services/City/CityParticipantsServiceTests.cs
  EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
  EPlast/EPlast.Tests/Services/EmailSending/NewPlastMemberEmailGreetingTests.cs
  EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
  EPlast/EPlast.Tests/Services/UserProfiles/UserRenewalServiceTests.cs
  EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
  EPlast/EPlast.WebApi/StartupExtensions/AddDependenciesExtension.cs
  EPlast/EPlast.XUnitTest/EPlast.XUnitTest.csproj
  EPlast/EPlast.XUnitTest/ExtentionMethods/GetDecisionStatusTypesExtentionTest.cs
  EPlast/EPlast.XUnitTest/Handlers/Decision/DeleteDecisionAsyncHandlerTest.cs
  EPlast/EPlast.XUnitTest/Handlers/Decision/DownloadDecisionFileFromBlobAsyncHandlerTest.cs
  EPlast/EPlast.XUnitTest/Handlers/Decision/GetDecisionAsyncHandlerTest.cs
  EPlast/EPlast.XUnitTest/Handlers/Decision/GetDecisionListAsyncHandlerTest.cs
  EPlast/EPlast.XUnitTest/Handlers/Decision/GetDecisionOrganizationAsyncHandlerTest.cs
  EPlast/EPlast.XUnitTest/Handlers/Decision/SaveDecisionAsyncHandlerTest.cs
  EPlast/EPlast.XUnitTest/Handlers/Decision/UpdateHandlerTest.cs
  EPlast/EPlast.XUnitTest/Services/Decision/DecisionServiceTests.cs
Labels: Decisions (Рішення)

#2369 Possibility to create event without alternate
  EPlast/EPlast.BLL/Services/EventUser/EventUserManager.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventUserManagerTests.cs
Labels: Bug, Events (події)

#2372 Governing bodies select admins fix and upgrade
  EPlast/EPlast.BLL/DTO/UserProfiles/ShortUserInformationDTO.cs
  EPlast/EPlast.BLL/Interfaces/Admin/IAdminService.cs
  EPlast/EPlast.BLL/Services/Admin/AdminService.cs
  EPlast/EPlast.BLL/Services/GoverningBodies/GoverningBodyAdministrationService.cs
  EPlast/EPlast.BLL/Services/GoverningBodies/Sector/SectorAdministrationService.cs
  EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
  EPlast/EPlast.Tests/Services/Admin/AdminServiceTests.cs
  EPlast/EPlast.WebApi/Controllers/AdminController.cs
Labels: Bug, Governing Bodies(Керівні Органи), Governing Body's Sectors(Напрями)

#2346 Corrected spelling mistake
  EPlast/EPlast.BLL/Services/PDF/Documents/BlankDocument.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/User.cs
Labels: Bug, UI

#2373 City Admin can assign any degree to members of his city through the …
  EPlast/EPlast.Tests/Controllers/ActiveMembershipControllerTests.cs
  EPlast/EPlast.WebApi/Controllers/ActiveMembershipController.cs
Labels: Users Table (Таблиця користувачів), Рівні доступу (Access Levels)

#2366 Bug/2201 not list previously roles
  EPlast/EPlast.BLL/Interfaces/Region/IRegionAdministrationService.cs
  EPlast/EPlast.BLL/Services/Region/RegionAdministrationService.cs
  EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
  EPlast/EPlast.Tests/Services/Regions/RegionAdministrationServiceTests.cs
  EPlast/EPlast.WebApi/Controllers/RegionsController.cs
Labels: Bug
