Repository ita-social-projects/EPlast, pull requests merged in 2022-07, with the labels that each got.

#2610 Fix for link in City provid
  EPlast/EPlast.BLL/Handlers/CityHandlers/GetCityByIdWthFullInfoHandler.cs
Labels: Cities (станиці)

#2605 Modify CreateFollower logic and add Get SuperAdmins endpoint for notifications
  EPlast/EPlast.BLL/Interfaces/Region/IRegionService.cs
  EPlast/EPlast.BLL/Services/Region/RegionService.cs
  EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
  EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
  EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
  EPlast/EPlast.WebApi/Controllers/AdminController.cs
  EPlast/EPlast.WebApi/Controllers/RegionsController.cs
Labels: Cities (станиці), Regions (Округи)

#2613 Fix RegionFollower migration
  EPlast/EPlast.DataAccess/Migrations/20220701065839_AddOblastToRegionFollower.cs
Labels: Bug

#2608 order by name of entity
  EPlast/EPlast.BLL/DTO/Decision/DecisionTargetDTO.cs
  EPlast/EPlast.BLL/Handlers/RegionHandlers/GetAllRegionsByPageAndIsArchiveHandler.cs
  EPlast/EPlast.DataAccess/Repositories/Realizations/City/CityRepository.cs
Labels: Cities (станиці), Regions (Округи)

#2536 add LastAsync in Service
  EPlast/EPlast.BLL/Interfaces/MethodicDocument/IMethodicDocumentService.cs
  EPlast/EPlast.BLL/Services/MethodicDocument/MethodicDocumentService.cs
  EPlast/EPlast.WebApi/Controllers/MethodicDocumentsController.cs
Labels: Legislation (Репозитарій)

#2617 Ignore local SonarScanner results
  .gitignore
Labels: .NET

#2627 add directory access
  EPlast/EPlast.WebApi/AccessSecurityModel/MenuAccessSettings.json
Labels: Accessibility ♿

#2642 Fix Regions Creation
  EPlast/EPlast.BLL/DTO/Region/RegionProfileDTO.cs
Labels: Regions (Округи)

#2638 Exclude admin option from adding precaution
  EPlast/EPlast.BLL/Services/Precautions/UserPrecautionService.cs
Labels: Precaution (Перестороги)

#2637 Added filter to all referent roles on user table
  EPlast/EPlast.BLL/Services/Admin/AdminService.cs
Labels: Users Table (Таблиця користувачів), Рівні доступу (Access Levels)

#2652 Fix switcher
  EPlast/EPlast.DataAccess/Repositories/Realizations/City/CityRepository.cs
  EPlast/EPlast.WebApi/Controllers/CitiesController.cs
Labels: Cities (станиці), Regions (Округи)

#2658 Change Oblast in Region Fix
  EPlast/EPlast.BLL/Services/Region/RegionService.cs
Labels: Type: Maintenances, Regions (Округи)

#2661 Add comment for RemoveFollower option and UT filter for followers
  EPlast/EPlast.BLL/DTO/UserProfiles/UserTableDTO.cs
  EPlast/EPlast.BLL/Interfaces/City/ICityParticipantsService.cs
  EPlast/EPlast.BLL/Interfaces/EmailSending/IEmailContentService.cs
  EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
  EPlast/EPlast.BLL/Services/EmailSending/EmailContentService.cs
  EPlast/EPlast.DataAccess/Entities/UserEntities/UserTableObject.cs
  EPlast/EPlast.DataAccess/Repositories/Realizations/Admin/AdminTypeRepository.cs
  EPlast/EPlast.Tests/Controllers/CityControllerTests.cs
  EPlast/EPlast.Tests/Services/City/CityParticipantsServiceTests.cs
  EPlast/EPlast.Tests/Services/EmailSending/EmailContentServiceTests.cs
  EPlast/EPlast.WebApi/Controllers/CitiesController.cs
Labels: Users Table (Таблиця користувачів)

#2675 Hide Regional Board for registered user
  EPlast/EPlast.WebApi/AccessSecurityModel/MenuAccessSettings.json
Labels: Рівні доступу (Access Levels), Menu

#2680 Fix duplicating Supporter role when assigning a "Пластрият" degree
  EPlast/EPlast.BLL/Services/ActiveMembership/AccessLevelService.cs
  EPlast/EPlast.BLL/Services/ActiveMembership/PlastDegreeService.cs
  EPlast/EPlast.Tests/Services/ActiveMembership/AccessLevelServiceTests.cs
  EPlast/EPlast.Tests/Services/ActiveMembership/PlastDegreeServiceTests.cs
  EPlast/EPlast.WebApi/Controllers/ActiveMembershipController.cs
Labels: Bug, Degree

#2676 Fix cities order
  EPlast/EPlast.DataAccess/Repositories/Realizations/City/CityRepository.cs
Labels: Cities (станиці)

#2682 Fix for users with multiple referent roles
  EPlast/EPlast.BLL/Services/Admin/AdminService.cs
  EPlast/EPlast.Tests/Services/Admin/AdminServiceTests.cs
Labels: Users Table (Таблиця користувачів)
