Repository ita-social-projects/EPlast, pull requests merged in 2022-05, with the labels that each got.

#2395 Updated Roles - GoverningBodyAdmin has the same access levels as SuperAdmin.
  EPlast/EPlast.Resources/Roles.cs
Labels: Рівні доступу (Access Levels)

#2396 Updated GoverningBodyAdmin access levels at Profile
  EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
  EPlast/EPlast.WebApi/Controllers/UserController.cs
Labels: Рівні доступу (Access Levels)

#2397 Updated GoverningBodyAdmin access levels at AnnualReports
  EPlast/EPlast.BLL/Services/City/CityAccess/CityAccessService.cs
  EPlast/EPlast.BLL/Settings/CityAccessSettings.cs
  EPlast/EPlast.BLL/Settings/ClubAccessSettings.cs
  EPlast/EPlast.BLL/Settings/RegionAccessSettings.cs
Labels: Рівні доступу (Access Levels)

#2398 Updated GoverningBodyAdmin access levels at Distinctions
  EPlast/EPlast.BLL/Services/Distinctions/UserDistinctionService.cs
  EPlast/EPlast.Resources/Roles.cs
  EPlast/EPlast.WebApi/Controllers/DistinctionController.cs
Labels: Рівні доступу (Access Levels)

#2418 Empty announcements fix
  EPlast/EPlast.BLL/EPlast.BLL.csproj
  EPlast/EPlast.BLL/Interfaces/GoverningBodies/Announcement/IHtmlService.cs
  EPlast/EPlast.BLL/Services/GoverningBodies/Announcement/GoverningBodyAnnouncementService.cs
  EPlast/EPlast.BLL/Services/GoverningBodies/Announcement/HtmlService.cs
  EPlast/EPlast.BLL/Services/GoverningBodies/Sector/SectorAnnouncementsService.cs
  EPlast/EPlast.Tests/Controllers/GoverningBodiesControllerTests.cs
  EPlast/EPlast.Tests/Controllers/GoverningBodySectorsControllerTests.cs
  EPlast/EPlast.Tests/Services/GoverningBody/Announcement/GoverningBodyAnnouncementServiceTest.cs
  EPlast/EPlast.Tests/Services/GoverningBody/Announcement/HtmlServiceTests.cs
  EPlast/EPlast.Tests/Services/GoverningBody/Sector/SectorAnnouncementsServiceTests.cs
  EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
  EPlast/EPlast.WebApi/Controllers/GoverningBodySectorsController.cs
  EPlast/EPlast.WebApi/StartupExtensions/AddDependenciesExtension.cs
Labels: Bug, Governing Bodies(Керівні Органи), Governing Body's Sectors(Напрями)

#2423 Wrong user cannot reject other user
  EPlast/EPlast.WebApi/Controllers/EventsController.cs
Labels: Bug, Events (події), Postman

#2424 Menu item is visible in menu for a Registered User #2420
  EPlast/EPlast.WebApi/AccessSecurityModel/MenuAccessSettings.json
Labels: Bug, Events (події), registered user

#2489 Fixed bug 2385
  EPlast/EPlast.BLL/Services/EventUser/EventUserManager.cs
  EPlast/EPlast.Tests/Controllers/EventsUsersControllerTests.cs
  EPlast/EPlast.WebApi/Controllers/EventsUsersController.cs
  EPlast/EPlast.XUnitTest/Services/Events/EventUserManagerTests.cs
Labels: Bug, Events (події), Postman

#2499 Fix City created as archived by Admin and GBAdmin
  EPlast/EPlast.WebApi/Controllers/CitiesController.cs
Labels: Cities (станиці)

#2506 Fix 2493
  EPlast/EPlast.BLL/Services/EventUser/EventUserAccess/EventUserAccessService.cs
  EPlast/EPlast.WebApi/Controllers/EventsUsersController.cs
Labels: Events (події)

#2491 Only return Approved Reports
  EPlast/EPlast.BLL/Services/Statistics/StatisticsService.cs
Labels: Improvement, Statistics

#2492 [HELP WANTED] Migrate from vs2017-win2016 to windows-2022 environment
  azure-pipelines.yml
Labels: HELP WANTED

#2516 Create azure-pipelines-prod.yml
  azure-pipelines-prod.yml
Labels: HELP WANTED

#2478 Ignore .vscode folder
  .gitignore
Labels: .NET

#2512 Security fixed
  EPlast/EPlast.WebApi/AccessSecurityModel/MenuAccessSettings.json
  EPlast/EPlast.WebApi/Controllers/MethodicDocumentsController.cs
Labels: Bug, Legislation
